#!/usr/bin/env node
/**
 * Build script — bundles JSON data and SVG map into a single JS file
 * for offline / USB-stick use (avoids CORS errors with file:// protocol).
 *
 * Usage: node build.js
 *
 * Run this whenever you edit any file in data/ or images/map/.
 * The generated data/bundled.js is loaded by index.html automatically.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

function readJSON(filePath) {
    const text = fs.readFileSync(path.join(ROOT, filePath), 'utf8');
    // Validate JSON
    JSON.parse(text);
    return text;
}

function readText(filePath) {
    return fs.readFileSync(path.join(ROOT, filePath), 'utf8');
}

console.log('Building data bundle...');

const family   = readJSON('data/family.json');
const config   = readJSON('data/config.json');
const countries = readJSON('data/countries.json');
const worldMap = readText('images/map/world-map.svg');

const output = `// Auto-generated by build.js — do not edit directly.
// Run "node build.js" after editing files in data/ or images/map/.
window.BUNDLED_DATA = {
  family: ${family},
  config: ${config},
  countries: ${countries},
  worldMapSVG: ${JSON.stringify(worldMap)}
};
`;

const outPath = path.join(ROOT, 'data', 'bundled.js');
fs.writeFileSync(outPath, output, 'utf8');

const sizeKB = Math.round(fs.statSync(outPath).size / 1024);
console.log(`Done! data/bundled.js written (${sizeKB} KB)`);
